Improve support for sentry-java
getsentry/spotlight pull request #357
Opened 2024-02-12 09:29 UTC by markushi

When working on the Java/Android SDK side for spotlight integration https://github.com/getsentry/sentry-java/pull/3166 I stumbled upon two issues which caused spotlight to crash:
* `sentry-java` sends over "Message" events, which contain a top level [message object](https://develop.sentry.dev/sdk/event-payloads/message/), that clashes with the `message: string` of error events
* transactions may contain no spans at all

Before opening this PR:

- [x] I added a [Changeset Entry](https://spotlightjs.com/contribute/changesets/) with `pnpm changeset:add`
- [x] I referenced issues that this PR addresses

2024-02-12 09:35 UTC, markushi commented
A few captured samples when spinning our spring boot example:

[application_x_sentry_envelope-1707730398893.txt](https://github.com/getsentry/spotlight/files/14236807/application_x_sentry_envelope-1707730398893.txt)
[application_x_sentry_envelope-1707730421554.txt](https://github.com/getsentry/spotlight/files/14236808/application_x_sentry_envelope-1707730421554.txt)
[application_x_sentry_envelope-1707730422564.txt](https://github.com/getsentry/spotlight/files/14236809/application_x_sentry_envelope-1707730422564.txt)
[application_x_sentry_envelope-1707730424572.txt](https://github.com/getsentry/spotlight/files/14236810/application_x_sentry_envelope-1707730424572.txt)
[application_x_sentry_envelope-1707730433711.txt](https://github.com/getsentry/spotlight/files/14236811/application_x_sentry_envelope-1707730433711.txt)
[application_x_sentry_envelope-1707730434719.txt](https://github.com/getsentry/spotlight/files/14236812/application_x_sentry_envelope-1707730434719.txt)
[application_x_sentry_envelope-1707730435728.txt](https://github.com/getsentry/spotlight/files/14236813/application_x_sentry_envelope-1707730435728.txt)
[application_x_sentry_envelope-1707730436737.txt](https://github.com/getsentry/spotlight/files/14236814/application_x_sentry_envelope-1707730436737.txt)

2024-02-12 16:25 UTC, Shubhdeep12 requested changes
Hi @markushi added some suggestions, let make `type` attribute separate for both types of event - Error event and transaction.

2024-02-12 16:25 UTC, Shubhdeep12 commented on packages/overlay/src/integrations/sentry/components/Events/Event.tsx
> +import { SentryEvent } from '../../types';
```suggestion
import { SentryErrorEvent, SentryEvent } from '../../types';
```

2024-02-12 16:25 UTC, Shubhdeep12 commented on packages/overlay/src/integrations/sentry/components/Events/Event.tsx
> +export function EventTitle({ event }: { event: SentryEvent }) {
```suggestion
export function EventTitle({ event }: { event: SentryEvent | SentryErrorEvent }) {
```

2024-02-12 16:25 UTC, Shubhdeep12 commented on packages/overlay/src/integrations/sentry/components/Events/Event.tsx
> +export function EventSummary({ event }: { event: SentryEvent }) {
```suggestion
export function EventSummary({ event }: { event: SentryErrorEvent | SentryEvent }) {
```

2024-02-12 16:25 UTC, Shubhdeep12 commented on packages/overlay/src/integrations/sentry/components/Events/Event.tsx
> +export default function Event({ event }: { event: SentryEvent }) {
```suggestion
export default function Event({ event }: { event: SentryErrorEvent | SentryEvent }) {
```

2024-02-12 16:25 UTC, Shubhdeep12 commented on packages/overlay/src/integrations/sentry/types.ts
> +  type?: 'error' | 'event' | 'message' | 'default';
hi @markushi  any specific reason for moving this to `commonEventAttrs`?

2024-02-12 16:25 UTC, Shubhdeep12 commented on packages/overlay/src/integrations/sentry/types.ts
> +  type?: 'error' | 'event' | 'message' | 'default';
either we should add "transaction" here as well and remove the type from SentryEvent as well.

OR

lets revert this and move these types to SentryErrorEvent again.

2024-02-13 14:18 UTC, Shubhdeep12 commented on packages/overlay/src/integrations/sentry/data/sentryDataCache.ts
> +              txn.spans.map(s => ({
lets spread the array here 
```suggestion
              ...txn.spans.map(s => ({
```

2024-02-19 08:47 UTC, markushi commented on packages/overlay/src/integrations/sentry/types.ts
> +  spans?: Span[];
No unfortunately not, it can be either `null` or empty.

2024-02-19 17:12 UTC, Shubhdeep12 approved these changes
LGTM   🔎

2024-02-20 07:58 UTC, merged