feat: POC for adding spotlight overlay for ssr-errors
getsentry/spotlight pull request #364
Opened 2024-02-23 15:43 UTC by Shubhdeep12

Before opening this PR:

- [x] I added a [Changeset Entry](https://spotlightjs.com/contribute/changesets/) with `pnpm changeset:add`
- [x] I referenced issues that this PR addresses
#363 

https://vimeo.com/915998606/e0200955c6

- Added a new option in sentry integration to display the first incoming error - `showFirstIncomingError?: boolean`
- if passed as true, the first encountered error will be opened up automatically.
- Also, I closed Astro's custom error overlay and made changes to the plugin created by @Lms24 in @spotlight/astro to open spotlight in ssr-error page

2024-02-26 10:35 UTC, Lms24 reviewed
Your video shows the problem here pretty well: We're showing the island error although we actually should be showing the "random error" (SSR error) when it occurs. So maybe showing the _first_ error is not the way to go. Ideally, we rather want to show the most _recent_ error. This should be more correct in general but I guess there's the timing problem again.

Can you check if the SSR error is already sent to the overlay by the time the error page is rendered? If yes, we _should_ be good.

Another idea I just had (gonna note it down here so we don't completely forget):

We could try this (NO idea if it works). 

- We register an event processor on the server SDK that writes the most recent eventId to the global object.
  - To try this, we can simply call something like this in an Astro test app:
     ```js
    Sentry.addEventProcessor(event => {
      if (!event.type) {
        globalThis.__Sentry_last_event_id = event.event_id;
      }
    })
     ```
  - If this works, we add it to the `Spotlight` integration in the Sentry JS SDK.
- In the vite plugin, we access the global object and get the id
- We add an option to the overlay init (something like `waitForEventId: string`) and if it is defined, we immediately open spotlight and wait for the event with the id to come in and show it. 

This requires the Vite plugin to run in the same process as the Astro dev server so that they actually share the global object. I believe this is the case but I never tried it out. Might be worth to explore though!

2024-02-26 10:45 UTC, Shubhdeep12 commented
Yes its worth trying. 

I'll try both the ideas out. 💡

2024-03-02 10:31 UTC, Shubhdeep12 commented
@Lms24 looks like the SSR error is sent to overlay by the time the error page is rendered and we can open the last error received to overlay - which is approach 1
I've pushed the code for this approach

2024-03-02 10:36 UTC, Shubhdeep12 commented
And @Lms24  when it comes to Approach 2, which is more logical in terms of error tracking, I tried this approach by adding Sentry.addEventProcessor in the Sentry.server.config.ts file in the demo app and tracked the event ID, as you suggested above.

I used that as the option in the Sentry integration while initializing the spotlight for the SSR-error page. This works for the first time, but I am not sure whether the Vite plugin caches the transform function created for the first time or something else, as it doesn't update the value retrieved from globalThis. Even if the value is updated, it always takes the value set for the first time.

2024-06-26 22:27 UTC, BYK requested changes

2024-06-26 22:27 UTC, BYK commented on packages/astro/src/snippets.ts
> +  fullPage: ${options.fullPage === true ? 'true' : 'false'},
Curious, why don't we do `Boolean(options.fullPage).toString()`? (and for all the others?)

Or even better, something like:

```js

const init_options = {
  integrations: integrationCalls,
  ...options,
};

return `Spotlight.init(${JSON.stringify(init_options))})`
```

2024-06-26 22:27 UTC, BYK commented on packages/astro/src/vite/error-page.ts
> +      // Checking if there is a ErrorOverlay class added by Astro
This definitely feels quite fragile. Do we do this kind of find/replace on actual JS/TS code somewhere?

2024-06-26 22:27 UTC, BYK commented on packages/overlay/src/integrations/sentry/index.ts
> +      if (options?.showRecentError && errorsCount) {
```suggestion
      if (errorsCount && options?.showRecentError) {
```

Cheaper (and easier on the eyes & mind) to check the count first.

2024-07-04 22:31 UTC, BYK approved these changes

2024-07-04 22:32 UTC, merged